### ISSUE TITLE
使用插件，无任何反应

### ISSUE THREAD

**Issue by pdm6688** [ygqygq2/turbo-console-log#1]
你好，我在使用插件时无任何反应，并未增加输出语句。
尝试过.js .py .go均未输出。
ps：在使用下载次数最多的turbo-console-log插件时是能够对js文件正常增加输出语句，应该不是我配置问题。

**Comment by ygqygq2** [comment]
你有自己额外配置吗？我自己机器测试没问题， - -!

**Comment by pdm6688** [comment]
没有任何配置，很奇怪。快捷键和命令面板都有尝试，全部没反应

**Comment by ygqygq2** [comment]
我知道问题了。默认logFunction 没有配置是空，我应该先判断它是否是数组。因为我把它类型改了，现在支持按语言配置它。
问题在于它不是数组时，我还用了find，所以就报错中止后面的操作了。
谢谢反馈。我修复下

**Comment by pdm6688** [comment]
好的，希望老哥能支持更多的语言输出😁
