### ISSUE TITLE
部分语言语法错误

### ISSUE THREAD

**Issue by pdm6688** [ygqygq2/turbo-console-log#2]
### **python**
print("🚀 ~ file: tt.py:12 ~ num:" num)
少个 , 应改为
print("🚀 ~ file: tt.py:12 ~ num:", num)

### **golang**
fmt.println("🚀 ~ file: testgo.go:16 ~ age:", age)
println中的p应改为大写
fmt.Println("🚀 ~ file: testgo.go:16 ~ age:", age)

js与ts正常，其他语言还未尝试

**Comment by ygqygq2** [comment]
好的，多谢。因为我也没写这么多语言，有时候 gpt  挨抽，尽出些低级错误误导我 😢

**Comment by pdm6688** [comment]
😄
