### ISSUE TITLE
从3.0.4版本开始不能通过crtl + alt + l 打印对象了(python)

### ISSUE THREAD

**Issue by yulk** [ygqygq2/turbo-console-log#4]
最后一个可用的版本为3.0.3

**Comment by ygqygq2** [comment]
你是什么系统，vscode 什么版本呢。我使用还是正常的。

**Comment by yulk** [comment]
WINDOWS 10 VSCODE 1.95.3. 就是直接看不到 crtl + alt + l 对应的功能了,按这个键也没有反应,卸载重装都试过.

**Comment by ygqygq2** [comment]
@yulk 我测试都正常，不知道是不是你有其它插件影响。
<img width="1378" alt="image" src="https://github.com/user-attachments/assets/807385fc-c3e2-404f-9430-31db1f8d1058">

**Comment by yulk** [comment]
![PixPin_2024-12-06_09-07-23](https://github.com/user-attachments/assets/720c2194-506e-49b4-a533-edb0e31cbc22)
升级后功能就消失了,我不知道怎么排除这个问题.

**Comment by yulk** [comment]
![image](https://github.com/user-attachments/assets/093919e5-23a9-4f1f-86a8-d68f98ef508f)
命令里也没有了.

**Comment by ygqygq2** [comment]
我看你最后一个截图有，第三行。变成了 Ctrl + Alt + P

**Comment by yulk** [comment]
> 我看你最后一个截图有，第三行。变成了 Ctrl + Alt + P

按你这个提示,搞定了,并且重新绑定到了 Ctrl + Alt + L  

"Ctrl + Alt + P“这个变化是版本带来的还是我不小心改过？

**Comment by yulk** [comment]
我把我的 配置文件清空就一切正常了。thanks！
![image](https://github.com/user-attachments/assets/70aac038-5cc7-43ca-a56c-ecc1e5dc8af5)

**Comment by ygqygq2** [comment]
应该是有部分配置冲突了，你一段段加减尝试，就可以找出来。没配置也不行，我也一堆配置，vscode 很多插件得自定义才好用。
